name: test
on: push
jobs:
  push:
    name: Push to GCS
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: google-github-actions/upload-cloud-storage@main
      with:
        credentials: ${{ secrets.TEST }}
        path: test
        destination: test
